### ISSUE TITLE
Absorbing batch norm into conv weights

### ISSUE THREAD

**Issue by revilokeb** [tidsp/caffe-jacinto#23]
The Readme says "A tool is provided to absorb batch norm values into convolution weights". Could anyone point me to that tool, which I dont seem to be able to find. Thx!

**Comment by mathmanu** [comment]
The code corresponding to this functionality is here:
https://github.com/tidsp/caffe-jacinto/blob/caffe-0.17/tools/caffe.cpp#L818

When you compile caffe-jacinto, there will be a binary called "optimize" which can do this.

**Comment by revilokeb** [comment]
@mathmanu many thanks, it seems to work.
