### ISSUE TITLE
Depthswise Convolution from existing Convolution Layer?

### ISSUE THREAD

**Issue by sagartesla** [tidsp/caffe-jacinto#28]
Hi,

I want to write MobileNet V1 and MobileNet V2 prototxt for caffe-jacinto. 
And these 2 architecture has depthwise covolution as basis building block. As per my understanding of existing Convolution Layer, We can use it as depthwise convolution layer by mentioning number outputs equal to number of groups in conv layer parameter.

Is my understanding correct?
If depthwise convolution layer can be written using existing convolution layer, then why there is need to introduce new ConvolutionDepthwise Layer ?

Ref: TODO in the next release (not yet added): sp2823/caffe, BVCL/caffe/pull/5665 - ConvolutionDepthwise layer for faster depthwise separable convolutions.

Regards,
Sagar

**Comment by mathmanu** [comment]
Existing Convolution layer type can support depthwise convolutions as well. That TODO was only to speedup the execution of depthwise convolution layers.
