### ISSUE TITLE
Problem in the build of caffe-jacinto caffe-0.16

### ISSUE THREAD

**Issue by Wronskia** [tidsp/caffe-jacinto#5]
Hello,

there is a little problem during the installation with boost::basic_regex. I created a pull request that solves this problem.

Thank you,
Yassine

[ 98%] Linking CXX executable extract_features
cd /opt/caffe-jacinto/caffe-jacinto/build/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/extract_features.dir/link.txt --verbose=1
/usr/bin/c++    -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized -O3 -DNDEBUG   CMakeFiles/extract_features.dir/extract_features.cpp.o  -o extract_features -rdynamic ../lib/libcaffe-nv.so.0.16.4 ../lib/libproto.a -lboost_system -lboost_thread -lboost_filesystem -lboost_chrono -lboost_date_time -lboost_atomic -lpthread -lpthread -lglog -lgflags -lprotobuf /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so -lsz -lz -ldl -lm -lpthread -lpthread -lglog -lgflags -lprotobuf /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so -lsz -lz -ldl -lm -llmdb -lleveldb -lsnappy /usr/local/cuda/lib64/libcudart.so /usr/local/cuda/lib64/libcurand.so /usr/local/cuda/lib64/libcublas.so -lcudnn /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9 /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.9 /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.9 -llapack_atlas -lcblas -latlas -lpython2.7 -lboost_python /usr/local/lib/libnccl.so -lnvidia-ml -Wl,-rpath,/opt/caffe-jacinto/caffe-jacinto/build/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib:/usr/local/cuda/lib64:/usr/local/lib:::::::: 
../lib/libcaffe-nv.so.0.16.4: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:139: recipe for target 'tools/upgrade_solver_proto_text' failed
make[2]: Leaving directory '/opt/caffe-jacinto/caffe-jacinto/build'
make[2]: *** [tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:479: recipe for target 'tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
../lib/libcaffe-nv.so.0.16.4: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
collect2: error: ld returned 1 exit status

**Comment by mathmanu** [comment]
This was fixed for LINUX by adding boost_regex at line 284 in Makefile
	LIBRARIES += boost_thread boost_regex stdc++
But I guess you are not using linux. 

How about a small change in the patch that you submitted. In Dependencies.cmake add regex in line 5. Remove the list() line that you added.
find_package(Boost 1.46 REQUIRED COMPONENTS system thread filesystem **regex**)

Can you please test this and let me know.

**Comment by Wronskia** [comment]
Actually, I am using Ubuntu 16.04. 
Also, in https://github.com/NVIDIA/caffe branch caffe-0.16, the boost::basic_regex issue does not occur.
I tested  find_package(Boost 1.46 REQUIRED COMPONENTS system thread filesystem regex) but it still

**Comment by mathmanu** [comment]
Thanks. The PR has been merged.
